### ISSUE TITLE
Request-->POST http://localhost:8888/api/networkData HTTP/1.1,Request Headers-->{} org.apache.http.conn.HttpHostConnectException: Connect to localhost:8888 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect

### ISSUE THREAD

**Issue by ViharJam** [bpant12/SyncApp#2]
```
Hi am getting above error. Am using the same code as of yours only changed the path of chrome.
ChromeDriverService chromeDriverService = new ChromeDriverService.Builder().usingDriverExecutable(new File("D:\\git_work\\SyncAppClient\\" + "chromedriver.exe")).usingAnyFreePort().build(); 

Below is the complete stack trace.
Request-->POST http://localhost:8888/api/networkData HTTP/1.1,Request Headers-->{}
org.apache.http.conn.HttpHostConnectException: Connect to localhost:8888 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at com.syncapp.util.http.HTTPHelper.post(HTTPHelper.java:88)
	at com.syncapp.util.http.HTTPHelper.execute(HTTPHelper.java:65)
	at com.syncapp.util.devtool.SyncappUtil._submitTrackedData(SyncappUtil.java:142)
	at com.syncapp.util.devtool.SyncappUtil.endTracking(SyncappUtil.java:53)
	at TestSelenium.main(TestSelenium.java:62)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	... 15 more
```

**Comment by bpant12** [comment]
I have updated ReadMe file.
You need to get SyncApp server Docker image as well
I have mentioned all commands there . Follow them .
When the docker containers as up and running hit http://your IP:8089/api/networkData and this should not give connection refuse
If everything working fine then change config.json like
{
  "local":{
    "url":"http://your ip:8089"
  },

**Comment by bpant12** [comment]
closing the issue as there is no issue raised further here.
